// <auto-generated />
using System;
using BaseFaq.Common.EntityFramework.Tenant;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseFaq.Common.EntityFramework.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalCustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEventCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_BillingCustomer_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_BillingCustomer_TenantId");

                    b.HasIndex("Provider", "ExternalCustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_BillingCustomer_Provider_ExternalCustomerId");

                    b.HasIndex("TenantId", "Provider")
                        .HasDatabaseName("IX_BillingCustomer_TenantId_Provider");

                    b.ToTable("BillingCustomers", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalInvoiceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HostedUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEventCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("RawSnapshotJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_BillingInvoice_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_BillingInvoice_TenantId");

                    b.HasIndex("TenantSubscriptionId");

                    b.HasIndex("Provider", "ExternalInvoiceId")
                        .IsUnique()
                        .HasDatabaseName("IX_BillingInvoice_Provider_ExternalInvoiceId");

                    b.HasIndex("TenantId", "Status", "PaidAtUtc")
                        .HasDatabaseName("IX_BillingInvoice_TenantId_Status_PaidAtUtc");

                    b.ToTable("BillingInvoices", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("BillingInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalPaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEventCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("RawSnapshotJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BillingInvoiceId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_BillingPayment_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_BillingPayment_TenantId");

                    b.HasIndex("Provider", "ExternalPaymentId")
                        .IsUnique()
                        .HasDatabaseName("IX_BillingPayment_Provider_ExternalPaymentId")
                        .HasFilter("\"ExternalPaymentId\" IS NOT NULL");

                    b.HasIndex("TenantId", "Status", "PaidAtUtc")
                        .HasDatabaseName("IX_BillingPayment_TenantId_Status_PaidAtUtc");

                    b.ToTable("BillingPayments", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingProviderSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalPriceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalProductId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEventCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("RawSnapshotJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TrialEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_BillingProviderSubscription_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_BillingProviderSubscription_TenantId");

                    b.HasIndex("TenantSubscriptionId");

                    b.HasIndex("Provider", "ExternalSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_BillingProviderSubscription_Provider_ExternalSubscriptionId");

                    b.HasIndex("TenantId", "TenantSubscriptionId")
                        .HasDatabaseName("IX_BillingProviderSubscription_TenantId_TenantSubscriptionId");

                    b.ToTable("BillingProviderSubscriptions", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingWebhookInbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EventCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiveMode")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAttemptDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LockedUntilDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessingToken")
                        .HasColumnType("uuid");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ReceivedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Signature")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("SignatureValid")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_BillingWebhookInbox_IsDeleted");

                    b.HasIndex("ReceivedDateUtc")
                        .HasDatabaseName("IX_BillingWebhookInbox_ReceivedDateUtc");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_BillingWebhookInbox_TenantId");

                    b.HasIndex("Provider", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("IX_BillingWebhookInbox_Provider_ExternalEventId");

                    b.HasIndex("Status", "NextAttemptDateUtc", "LockedUntilDateUtc")
                        .HasDatabaseName("IX_BillingWebhookInbox_Status_NextAttempt_LockedUntil");

                    b.ToTable("BillingWebhookInboxes", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.EmailOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FromName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAttemptDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LockedUntilDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessingToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("QueuedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TextBody")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_EmailOutbox_IsDeleted");

                    b.HasIndex("QueuedDateUtc")
                        .HasDatabaseName("IX_EmailOutbox_QueuedDateUtc");

                    b.HasIndex("Status", "NextAttemptDateUtc", "LockedUntilDateUtc")
                        .HasDatabaseName("IX_EmailOutbox_Status_NextAttempt_LockedUntil");

                    b.ToTable("EmailOutboxes", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Edition")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Module")
                        .HasColumnType("integer")
                        .HasColumnName("Module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenant_ClientKey");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Tenant_IsDeleted");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenant_Slug");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.TenantConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Module")
                        .HasColumnType("integer")
                        .HasColumnName("Module");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_TenantConnection_IsDeleted");

                    b.HasIndex("Module", "IsCurrent")
                        .HasDatabaseName("IX_TenantConnection_Module_IsCurrent");

                    b.ToTable("TenantConnections", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.TenantEntitlementSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInGracePeriod")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_TenantEntitlementSnapshot_IsDeleted");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantEntitlementSnapshot_TenantId");

                    b.HasIndex("IsActive", "IsInGracePeriod", "EffectiveUntilUtc")
                        .HasDatabaseName("IX_TenantEntitlementSnapshot_IsActive_IsInGracePeriod_EffectiveUntilUtc");

                    b.ToTable("TenantEntitlementSnapshots", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BillingInterval")
                        .HasColumnType("integer");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultProvider")
                        .HasColumnType("integer");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GraceUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEventCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TrialEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_TenantSubscription_IsDeleted");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantSubscription_TenantId");

                    b.HasIndex("Status", "CurrentPeriodEndUtc")
                        .HasDatabaseName("IX_TenantSubscription_Status_CurrentPeriodEndUtc");

                    b.ToTable("TenantSubscriptions", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_TenantUser_IsDeleted");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TenantUser_UserId");

                    b.HasIndex("TenantId", "Role")
                        .HasDatabaseName("IX_TenantUser_TenantId_Role");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantUser_TenantId_UserId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("TenantUsers", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SurName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_User_ExternalId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_User_IsDeleted");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingInvoice", b =>
                {
                    b.HasOne("BaseFaq.Common.EntityFramework.Tenant.Entities.TenantSubscription", "TenantSubscription")
                        .WithMany("Invoices")
                        .HasForeignKey("TenantSubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TenantSubscription");
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingPayment", b =>
                {
                    b.HasOne("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingInvoice", "BillingInvoice")
                        .WithMany("Payments")
                        .HasForeignKey("BillingInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BillingInvoice");
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingProviderSubscription", b =>
                {
                    b.HasOne("BaseFaq.Common.EntityFramework.Tenant.Entities.TenantSubscription", "TenantSubscription")
                        .WithMany("ProviderSubscriptions")
                        .HasForeignKey("TenantSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenantSubscription");
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.TenantUser", b =>
                {
                    b.HasOne("BaseFaq.Common.EntityFramework.Tenant.Entities.Tenant", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseFaq.Common.EntityFramework.Tenant.Entities.User", "User")
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.BillingInvoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.Tenant", b =>
                {
                    b.Navigation("TenantUsers");
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.TenantSubscription", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("ProviderSubscriptions");
                });

            modelBuilder.Entity("BaseFaq.Common.EntityFramework.Tenant.Entities.User", b =>
                {
                    b.Navigation("TenantUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
