// <auto-generated />
using System;
using BaseFaq.QnA.Common.Persistence.QnADb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseFaq.QnA.Common.Persistence.QnADb.Migrations
{
    [DbContext(typeof(QnADbContext))]
    [Migration("20260416045414_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApplicabilityRulesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("AuthorLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Body")
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<string>("ContextKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCanonical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrustNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Answer_IsDeleted");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Answer_TenantId");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.AnswerSourceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_AnswerSourceLink_IsDeleted");

                    b.HasIndex("SourceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AnswerSourceLink_TenantId");

                    b.HasIndex("AnswerId", "SourceId", "Role", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_AnswerSourceLink_AnswerId_SourceId_Role_Order");

                    b.ToTable("AnswerSourceLinks", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.KnowledgeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowsPublicCitation")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowsPublicExcerpt")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsAuthoritative")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Scope")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SystemName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_KnowledgeSource_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_KnowledgeSource_TenantId");

                    b.ToTable("KnowledgeSources", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedAnswerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AudienceScope")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<string>("ContextKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContextNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DuplicateOfQuestionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JourneyScope")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OriginChannel")
                        .HasColumnType("integer");

                    b.Property<string>("OriginReference")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("OriginUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProductScope")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThreadSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedAnswerId");

                    b.HasIndex("DuplicateOfQuestionId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Question_IsDeleted");

                    b.HasIndex("SpaceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Question_TenantId");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("IX_Question_TenantId_Key");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSourceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_QuestionSourceLink_IsDeleted");

                    b.HasIndex("SourceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_QuestionSourceLink_TenantId");

                    b.HasIndex("QuestionId", "SourceId", "Role", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_QuestionSourceLink_QuestionId_SourceId_Role_Order");

                    b.ToTable("QuestionSourceLinks", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcceptsAnswers")
                        .HasColumnType("boolean");

                    b.Property<bool>("AcceptsQuestions")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JourneyScope")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModerationPolicy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductScope")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresAnswerReview")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresQuestionReview")
                        .HasColumnType("boolean");

                    b.Property<int>("SearchMarkupMode")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_QuestionSpace_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_QuestionSpace_TenantId");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("IX_QuestionSpace_TenantId_Key");

                    b.ToTable("QuestionSpaces", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSpaceSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KnowledgeSourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionSpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_QuestionSpaceSource_IsDeleted");

                    b.HasIndex("KnowledgeSourceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_QuestionSpaceSource_TenantId");

                    b.HasIndex("QuestionSpaceId", "KnowledgeSourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_QuestionSpaceSource_QuestionSpaceId_KnowledgeSourceId");

                    b.ToTable("QuestionSpaceSources", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSpaceTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionSpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_QuestionSpaceTopic_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_QuestionSpaceTopic_TenantId");

                    b.HasIndex("TopicId");

                    b.HasIndex("QuestionSpaceId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("IX_QuestionSpaceTopic_QuestionSpaceId_TopicId");

                    b.ToTable("QuestionSpaceTopics", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_QuestionTopic_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_QuestionTopic_TenantId");

                    b.HasIndex("TopicId");

                    b.HasIndex("QuestionId", "TopicId")
                        .IsUnique()
                        .HasDatabaseName("IX_QuestionTopic_QuestionId_TopicId");

                    b.ToTable("QuestionTopics", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.ThreadActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActorKind")
                        .HasColumnType("integer");

                    b.Property<string>("ActorLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotJson")
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ThreadActivity_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ThreadActivity_TenantId");

                    b.HasIndex("QuestionId", "OccurredAtUtc")
                        .HasDatabaseName("IX_ThreadActivity_QuestionId_OccurredAtUtc");

                    b.ToTable("ThreadActivities", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Topic_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Topic_TenantId");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("IX_Topic_TenantId_Name");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.AnswerSourceLink", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", "Answer")
                        .WithMany("Sources")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.KnowledgeSource", "Source")
                        .WithMany("Answers")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", "AcceptedAnswer")
                        .WithMany()
                        .HasForeignKey("AcceptedAnswerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "DuplicateOfQuestion")
                        .WithMany("DuplicateQuestions")
                        .HasForeignKey("DuplicateOfQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSpace", "Space")
                        .WithMany("Questions")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedAnswer");

                    b.Navigation("DuplicateOfQuestion");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSourceLink", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "Question")
                        .WithMany("Sources")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.KnowledgeSource", "Source")
                        .WithMany("Questions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSpaceSource", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.KnowledgeSource", "KnowledgeSource")
                        .WithMany("Spaces")
                        .HasForeignKey("KnowledgeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSpace", "QuestionSpace")
                        .WithMany("Sources")
                        .HasForeignKey("QuestionSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeSource");

                    b.Navigation("QuestionSpace");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSpaceTopic", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSpace", "QuestionSpace")
                        .WithMany("Topics")
                        .HasForeignKey("QuestionSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Topic", "Topic")
                        .WithMany("Spaces")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionSpace");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionTopic", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "Question")
                        .WithMany("Topics")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.ThreadActivity", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", "Answer")
                        .WithMany("Activities")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "Question")
                        .WithMany("Activities")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.KnowledgeSource", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Spaces");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Answers");

                    b.Navigation("DuplicateQuestions");

                    b.Navigation("Topics");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSpace", b =>
                {
                    b.Navigation("Sources");

                    b.Navigation("Topics");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Topic", b =>
                {
                    b.Navigation("Spaces");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
