// <auto-generated />
using System;
using BaseFaq.QnA.Common.Persistence.QnADb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseFaq.QnA.Common.Persistence.QnADb.Migrations
{
    [DbContext(typeof(QnADbContext))]
    [Migration("20260426001555_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActorKind")
                        .HasColumnType("integer");

                    b.Property<string>("ActorLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UserPrint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Activity_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Activity_TenantId");

                    b.HasIndex("QuestionId", "OccurredAtUtc")
                        .HasDatabaseName("IX_Activity_QuestionId_OccurredAtUtc");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AiConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<string>("AuthorLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Body")
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)");

                    b.Property<string>("ContextNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Answer_IsDeleted");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Answer_TenantId");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.AnswerSourceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_AnswerSourceLink_IsDeleted");

                    b.HasIndex("SourceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AnswerSourceLink_TenantId");

                    b.HasIndex("AnswerId", "SourceId", "Role", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_AnswerSourceLink_AnswerId_SourceId_Role_Order");

                    b.ToTable("AnswerSourceLinks", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedAnswerId")
                        .HasColumnType("uuid");

                    b.Property<int>("AiConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContextNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DuplicateOfQuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("FeedbackScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OriginChannel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedAnswerId");

                    b.HasIndex("DuplicateOfQuestionId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Question_IsDeleted");

                    b.HasIndex("SpaceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Question_TenantId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSourceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_QuestionSourceLink_IsDeleted");

                    b.HasIndex("SourceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_QuestionSourceLink_TenantId");

                    b.HasIndex("QuestionId", "SourceId", "Role", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_QuestionSourceLink_QuestionId_SourceId_Role_Order");

                    b.ToTable("QuestionSourceLinks", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_QuestionTag_IsDeleted");

                    b.HasIndex("TagId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_QuestionTag_TenantId");

                    b.HasIndex("QuestionId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("IX_QuestionTag_QuestionId_TagId");

                    b.ToTable("QuestionTags", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowsPublicCitation")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowsPublicExcerpt")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContextNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsAuthoritative")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Source_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Source_TenantId");

                    b.ToTable("Sources", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcceptsAnswers")
                        .HasColumnType("boolean");

                    b.Property<bool>("AcceptsQuestions")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Space_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Space_TenantId");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("IX_Space_TenantId_Key");

                    b.ToTable("Spaces", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.SpaceSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_SpaceSource_IsDeleted");

                    b.HasIndex("SourceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SpaceSource_TenantId");

                    b.HasIndex("SpaceId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_SpaceSource_SpaceId_SourceId");

                    b.ToTable("SpaceSources", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.SpaceTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_SpaceTag_IsDeleted");

                    b.HasIndex("TagId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SpaceTag_TenantId");

                    b.HasIndex("SpaceId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("IX_SpaceTag_SpaceId_TagId");

                    b.ToTable("SpaceTags", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Tag_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Tag_TenantId");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("IX_Tag_TenantId_Name");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Activity", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId");

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "Question")
                        .WithMany("Activities")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.AnswerSourceLink", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", "Answer")
                        .WithMany("Sources")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Source", "Source")
                        .WithMany("Answers")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", "AcceptedAnswer")
                        .WithMany()
                        .HasForeignKey("AcceptedAnswerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "DuplicateOfQuestion")
                        .WithMany("DuplicateQuestions")
                        .HasForeignKey("DuplicateOfQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Space", "Space")
                        .WithMany("Questions")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedAnswer");

                    b.Navigation("DuplicateOfQuestion");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionSourceLink", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "Question")
                        .WithMany("Sources")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Source", "Source")
                        .WithMany("Questions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.QuestionTag", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", "Question")
                        .WithMany("Tags")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Tag", "Tag")
                        .WithMany("Questions")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.SpaceSource", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Source", "Source")
                        .WithMany("Spaces")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Space", "Space")
                        .WithMany("Sources")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.SpaceTag", b =>
                {
                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Space", "Space")
                        .WithMany("Tags")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Tag", "Tag")
                        .WithMany("Spaces")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Answer", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Question", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Answers");

                    b.Navigation("DuplicateQuestions");

                    b.Navigation("Sources");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Source", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Questions");

                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Space", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Sources");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BaseFaq.QnA.Common.Persistence.QnADb.Entities.Tag", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Spaces");
                });
#pragma warning restore 612, 618
        }
    }
}
