services:
  querify.portal.app:
    image: querify.portal.app
    build:
      context: ../../..
      dockerfile: apps/portal/Dockerfile
    ports:
      - "5500:5500"
    environment:
      - VITE_PORTAL_TENANT_API_URL=${VITE_PORTAL_TENANT_API_URL:-//dev.portal.querify.net}
      - VITE_PORTAL_QNA_API_URL=${VITE_PORTAL_QNA_API_URL:-//dev.portal.querify.net}
      - VITE_AUTH0_DOMAIN=querify.us.auth0.com
      - VITE_AUTH0_AUDIENCE=https://querify.net
      - VITE_AUTH0_CLIENT_ID=U3WxjhBCMHAOCb5gDOXSYtdnTQViNb1K
      - VITE_AUTH0_PASSWORD_RESET_URL=
      - VITE_AUTH0_LOGOUT_URI=https://dev.portal.querify.net/logout
    networks:
      - qf-network

networks:
  qf-network:
    external: true
    name: qf-network
