namespace BaseFaq.Models.Broadcast.Enums;

/// <summary>
/// Identifies who produced a Broadcast item.
/// </summary>
public enum ActorKind
{
    /// <summary>
    /// Item was produced by an external audience member.
    /// </summary>
    ExternalUser = 1,

    /// <summary>
    /// Item was produced by the tenant brand or an authorized brand operator.
    /// </summary>
    Brand = 2,

    /// <summary>
    /// Item was generated by the system to record operational context in the thread.
    /// </summary>
    System = 3
}
