namespace BaseFaq.Direct.Common.Persistence.DirectDb.Enums;

/// <summary>
/// Identifies who wrote a support conversation message.
/// </summary>
public enum MessageActorKind
{
    /// <summary>
    /// Message was written by the customer or end user requesting support.
    /// </summary>
    User = 1,

    /// <summary>
    /// Message was generated by Support Copilot automation.
    /// </summary>
    Copilot = 2,

    /// <summary>
    /// Message was written by a human support agent.
    /// </summary>
    Agent = 3,

    /// <summary>
    /// Message was generated by the system to record operational context in the timeline.
    /// </summary>
    System = 4
}
