using BaseFaq.Common.EntityFramework.Core.Abstractions;
using BaseFaq.Common.EntityFramework.Core.Entities;

namespace BaseFaq.Faq.Common.Persistence.FaqDb.Entities;

public class FaqItem : BaseEntity, IMustHaveTenant
{
    public const int MaxQuestionLength = 1000;
    public const int MaxShortAnswerLength = 250;
    public const int MaxAnswerLength = 5000;
    public const int MaxAdditionalInfoLength = 2000;
    public const int MaxCtaTitleLength = 250;
    public const int MaxCtaUrlLength = 1000;

    /// <summary>
    /// Question text presented to the user.
    /// </summary>
    public required string Question { get; set; }

    /// <summary>
    /// Short answer or summary version of the response.
    /// Useful for previews, lists, or condensed displays.
    /// </summary>
    public required string ShortAnswer { get; set; }

    /// <summary>
    /// Full detailed answer for the question.
    /// </summary>
    public string? Answer { get; set; }

    /// <summary>
    /// Optional complementary information that adds context or clarifications.
    /// Does not replace the main answer.
    /// </summary>
    public string? AdditionalInfo { get; set; }

    /// <summary>
    /// Title of the call-to-action associated with this item.
    /// </summary>
    public string? CtaTitle { get; set; }

    /// <summary>
    /// URL of the call-to-action associated with this item.
    /// </summary>
    public string? CtaUrl { get; set; }

    /// <summary>
    /// Manual ordering value used when sort strategy is manual.
    /// </summary>
    public int Sort { get; set; }

    /// <summary>
    /// Cached score representing user feedback.
    /// Typically derived from associated feedback entries.
    /// </summary>
    public int FeedbackScore { get; set; }

    /// <summary>
    /// Confidence score generated by AI or automated processes.
    /// Represents estimated answer reliability.
    /// </summary>
    public int AiConfidenceScore { get; set; }

    /// <summary>
    /// Indicates whether this FAQ item is active and should be displayed.
    /// </summary>
    public bool IsActive { get; set; }

    public required Guid TenantId { get; set; }

    public required Guid FaqId { get; set; }
    public Faq Faq { get; set; } = null!;

    public Guid? ContentRefId { get; set; }
    public ContentRef? ContentRef { get; set; }

    public ICollection<Feedback> Feedbacks { get; set; } = [];
}
