services:
  basefaq.portal.app:
    image: basefaq.portal.app
    build:
      context: ..
      dockerfile: apps/portal/Dockerfile
    ports:
      - "5500:5500"
    environment:
      - VITE_PORTAL_TENANT_API_URL=https://dev.tenant.portal.basefaq.com
      - VITE_PORTAL_QNA_API_URL=https://dev.qna.portal.basefaq.com
      - VITE_AUTH0_DOMAIN=basefaq.us.auth0.com
      - VITE_AUTH0_AUDIENCE=https://basefaq.com
      - VITE_AUTH0_CLIENT_ID=fDJib60pSRhbtNRPhqYfZR9J8JqBCpz5
      - VITE_AUTH0_PASSWORD_RESET_URL=
      - VITE_AUTH0_LOGOUT_URI=https://dev.portal.basefaq.com/logout
    depends_on:
      - basefaq.qna.portal.api
      - basefaq.tenant.portal.api
    networks:
      - bf-network
  basefaq.qna.portal.api:
    image: basefaq.qna.portal.api
    build:
      context: ..
      dockerfile: dotnet/BaseFaq.QnA.Portal.Api/Dockerfile
    ports:
      - "5010:5010"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5010
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bf-network
  basefaq.tenant.backoffice.api:
    image: basefaq.tenant.backoffice.api
    build:
      context: ..
      dockerfile: dotnet/BaseFaq.Tenant.BackOffice.Api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bf-network
  basefaq.tenant.portal.api:
    image: basefaq.tenant.portal.api
    build:
      context: ..
      dockerfile: dotnet/BaseFaq.Tenant.Portal.Api/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bf-network
  basefaq.tenant.public.api:
    image: basefaq.tenant.public.api
    build:
      context: ..
      dockerfile: dotnet/BaseFaq.Tenant.Public.Api/Dockerfile
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5004
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bf-network
  basefaq.qna.public.api:
    image: basefaq.qna.public.api
    build:
      context: ..
      dockerfile: dotnet/BaseFaq.QnA.Public.Api/Dockerfile
    ports:
      - "5020:5020"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5020
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bf-network
  basefaq.tenant.worker.api:
    image: basefaq.tenant.worker.api
    build:
      context: ..
      dockerfile: dotnet/BaseFaq.Tenant.Worker.Api/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bf-network

networks:
  bf-network:
    external: true
    name: bf-network
