// <auto-generated />
using System;
using BaseFaq.Faq.Common.Persistence.FaqDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseFaq.Faq.Common.Persistence.FaqDb.Migrations
{
    [DbContext(typeof(FaqDbContext))]
    [Migration("20260408045127_FaqCtaAndFaqSortTypeRemoved")]
    partial class FaqCtaAndFaqSortTypeRemoved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.ContentRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Scope")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ContentRef_IsDeleted");

                    b.HasIndex("Kind")
                        .HasDatabaseName("IX_ContentRef_Kind");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ContentRef_TenantId");

                    b.ToTable("ContentRefs", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Faq_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Faq_TenantId");

                    b.ToTable("Faqs", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.FaqContentRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FaqId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentRefId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_FaqContentRef_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FaqContentRef_TenantId");

                    b.HasIndex("FaqId", "ContentRefId")
                        .IsUnique()
                        .HasDatabaseName("IX_FaqContentRef_FaqId_ContentRefId");

                    b.ToTable("FaqContentRefs", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.FaqItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("AiConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<string>("Answer")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid?>("ContentRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CtaTitle")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CtaUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FaqId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ShortAnswer")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VoteScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentRefId");

                    b.HasIndex("FaqId")
                        .HasDatabaseName("IX_FaqItem_FaqId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_FaqItem_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FaqItem_TenantId");

                    b.ToTable("FaqItems", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.FaqTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FaqId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_FaqTag_IsDeleted");

                    b.HasIndex("TagId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FaqTag_TenantId");

                    b.HasIndex("FaqId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("IX_FaqTag_FaqId_TagId");

                    b.ToTable("FaqTags", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Tag_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Tag_TenantId");

                    b.HasIndex("Value")
                        .HasDatabaseName("IX_Tag_Value");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FaqItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Like")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UnLikeReason")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UserPrint")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("FaqItemId")
                        .HasDatabaseName("IX_Vote_FaqItemId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Vote_IsDeleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Vote_TenantId");

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.FaqContentRef", b =>
                {
                    b.HasOne("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.ContentRef", "ContentRef")
                        .WithMany("Faqs")
                        .HasForeignKey("ContentRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Faq", "Faq")
                        .WithMany("ContentRefs")
                        .HasForeignKey("FaqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentRef");

                    b.Navigation("Faq");
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.FaqItem", b =>
                {
                    b.HasOne("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.ContentRef", "ContentRef")
                        .WithMany()
                        .HasForeignKey("ContentRefId");

                    b.HasOne("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Faq", "Faq")
                        .WithMany("Items")
                        .HasForeignKey("FaqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentRef");

                    b.Navigation("Faq");
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.FaqTag", b =>
                {
                    b.HasOne("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Faq", "Faq")
                        .WithMany("Tags")
                        .HasForeignKey("FaqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Tag", "Tag")
                        .WithMany("Faqs")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faq");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Vote", b =>
                {
                    b.HasOne("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.FaqItem", "FaqItem")
                        .WithMany("Votes")
                        .HasForeignKey("FaqItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaqItem");
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.ContentRef", b =>
                {
                    b.Navigation("Faqs");
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Faq", b =>
                {
                    b.Navigation("ContentRefs");

                    b.Navigation("Items");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.FaqItem", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("BaseFaq.Faq.Common.Persistence.FaqDb.Entities.Tag", b =>
                {
                    b.Navigation("Faqs");
                });
#pragma warning restore 612, 618
        }
    }
}
