// <auto-generated />
using System;
using BaseFaq.AI.Persistence.AiDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseFaq.AI.Persistence.AiDb.Migrations
{
    [DbContext(typeof(AiDbContext))]
    [Migration("20260213145000_AddProcessedMessageDedupe")]
    partial class AddProcessedMessageDedupe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseFaq.AI.Persistence.AiDb.Entities.GenerationArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArtifactType")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GenerationJobId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GenerationJobId")
                        .HasDatabaseName("IX_GenerationArtifact_GenerationJobId");

                    b.HasIndex("GenerationJobId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_GenerationArtifact_GenerationJobId_Sequence");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_GenerationArtifact_IsDeleted");

                    b.ToTable("GenerationArtifacts", (string)null);
                });

            modelBuilder.Entity("BaseFaq.AI.Persistence.AiDb.Entities.GenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("FaqId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromptProfile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("IX_GenerationJob_CorrelationId");

                    b.HasIndex("FaqId")
                        .HasDatabaseName("IX_GenerationJob_FaqId");

                    b.HasIndex("FaqId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_GenerationJob_FaqId_IdempotencyKey");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("IX_GenerationJob_IdempotencyKey");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_GenerationJob_IsDeleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_GenerationJob_Status");

                    b.ToTable("GenerationJobs", (string)null);
                });

            modelBuilder.Entity("BaseFaq.AI.Persistence.AiDb.Entities.ProcessedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ProcessedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HandlerName", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProcessedMessage_HandlerName_MessageId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ProcessedMessage_IsDeleted");

                    b.HasIndex("ProcessedUtc")
                        .HasDatabaseName("IX_ProcessedMessage_ProcessedUtc");

                    b.ToTable("ProcessedMessages", (string)null);
                });

            modelBuilder.Entity("BaseFaq.AI.Persistence.AiDb.Entities.GenerationArtifact", b =>
                {
                    b.HasOne("BaseFaq.AI.Persistence.AiDb.Entities.GenerationJob", "GenerationJob")
                        .WithMany("Artifacts")
                        .HasForeignKey("GenerationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationJob");
                });

            modelBuilder.Entity("BaseFaq.AI.Persistence.AiDb.Entities.GenerationJob", b =>
                {
                    b.Navigation("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
